window.SEED_ITEMS = [
  {
    "id": "belimbing-rice-terrace-1",
    "name": "Belimbing Rice Terrace",
    "category": "Rice Terraces",
    "query": "Belimbing Rice Terrace, Belimbing, Pupuan, Tabanan, Bali, Indonesia",
    "note": "Arrive before 09:00.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Belimbing Rice Terrace Bali"
  },
  {
    "id": "jatiluwih-rice-terraces-2",
    "name": "Jatiluwih Rice Terraces",
    "category": "Rice Terraces",
    "query": "Jatiluwih Rice Terraces, Jatiluwih, Penebel, Tabanan, Bali, Indonesia",
    "note": "Book a driver; not a great Grab-return location.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Jatiluwih",
    "imageQuery": "Jatiluwih Rice Terraces Bali"
  },
  {
    "id": "tegallalang-rice-terrace-3",
    "name": "Tegallalang Rice Terrace",
    "category": "Rice Terraces",
    "query": "Tegallalang Rice Terrace, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Most visited; go early. Swings, sky bike and zip line nearby.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Tegallalang Rice Terrace",
    "imageQuery": "Tegallalang Rice Terrace Bali"
  },
  {
    "id": "alas-harum-bali-4",
    "name": "Alas Harum Bali",
    "category": "Rice Terraces",
    "query": "Alas Harum Bali, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Rice terraces + photo/adventure complex. Cretya is here too.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Alas Harum Bali Bali"
  },
  {
    "id": "peking-rice-terrace-5",
    "name": "Peking Rice Terrace",
    "category": "Needs Confirmation",
    "query": "Peking Rice Terrace, Bali, Indonesia",
    "note": "Name needs confirmation; keep this card so we do not lose it.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Peking Rice Terrace Bali"
  },
  {
    "id": "pura-gunung-kawi-sebatu-6",
    "name": "Pura Gunung Kawi Sebatu",
    "category": "Water Temples",
    "query": "Pura Gunung Kawi Sebatu, Sebatu, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Water temple / purification stop.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Gunung Kawi",
    "imageQuery": "Pura Gunung Kawi Sebatu Bali"
  },
  {
    "id": "pura-mengening-7",
    "name": "Pura Mengening",
    "category": "Water Temples",
    "query": "Pura Mengening, Tampaksiring, Gianyar, Bali, Indonesia",
    "note": "Water purification.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Mengening Temple",
    "imageQuery": "Pura Mengening Bali"
  },
  {
    "id": "taman-beji-griya-waterfall-temple-8",
    "name": "Taman Beji Griya Waterfall Temple",
    "category": "Water Temples",
    "query": "Taman Beji Griya Waterfall, Punggul, Abiansemal, Badung, Bali, Indonesia",
    "note": "Hidden water temple. Merged with your duplicate Pura Taman Beji Griya Punggul entry.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Taman Beji Griya Waterfall Temple Bali"
  },
  {
    "id": "tirta-empul-temple-9",
    "name": "Tirta Empul Temple",
    "category": "Water Temples",
    "query": "Tirta Empul Temple, Tampaksiring, Gianyar, Bali, Indonesia",
    "note": "Busy; go early.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Tirta Empul",
    "imageQuery": "Tirta Empul Temple Bali"
  },
  {
    "id": "pura-segara-ulun-danu-batur-10",
    "name": "Pura Segara Ulun Danu Batur",
    "category": "Temples",
    "query": "Pura Segara Ulun Danu Batur, Lake Batur, Kintamani, Bangli, Bali, Indonesia",
    "note": "Lake Batur temple.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Lake Batur",
    "imageQuery": "Pura Segara Ulun Danu Batur Bali"
  },
  {
    "id": "ulun-danu-beratan-temple-11",
    "name": "Ulun Danu Beratan Temple",
    "category": "Temples",
    "query": "Ulun Danu Beratan Temple, Candikuning, Baturiti, Tabanan, Bali, Indonesia",
    "note": "Iconic lake temple at Bedugul.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Pura Ulun Danu Bratan",
    "imageQuery": "Ulun Danu Beratan Temple Bali"
  },
  {
    "id": "brahmavihara-arama-12",
    "name": "Brahmavihara-Arama",
    "category": "Temples",
    "query": "Brahmavihara-Arama, Banjar Tegeha, Buleleng, Bali, Indonesia",
    "note": "Buddhist monastery in North Bali.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Brahmavihara-Arama",
    "imageQuery": "Brahmavihara-Arama Bali"
  },
  {
    "id": "banyumala-twin-waterfalls-13",
    "name": "Banyumala Twin Waterfalls",
    "category": "Waterfalls",
    "query": "Banyumala Twin Waterfalls, Wanagiri, Sukasada, Buleleng, Bali, Indonesia",
    "note": "North Bali / Munduk area.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Banyumala Twin Waterfalls",
    "imageQuery": "Banyumala Twin Waterfalls Bali"
  },
  {
    "id": "tegenungan-waterfall-14",
    "name": "Tegenungan Waterfall",
    "category": "Waterfalls",
    "query": "Tegenungan Waterfall, Kemenuh, Sukawati, Gianyar, Bali, Indonesia",
    "note": "Omma Dayclub is beside the waterfall.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Tegenungan Waterfall",
    "imageQuery": "Tegenungan Waterfall Bali"
  },
  {
    "id": "banyu-wana-amertha-waterfall-15",
    "name": "Banyu Wana Amertha Waterfall",
    "category": "Waterfalls",
    "query": "Banyu Wana Amertha Waterfall, Wanagiri, Sukasada, Buleleng, Bali, Indonesia",
    "note": "North Bali.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Banyu Wana Amertha Waterfall Bali"
  },
  {
    "id": "gembleng-waterfall-16",
    "name": "Gembleng Waterfall",
    "category": "Waterfalls",
    "query": "Gembleng Waterfall, Tri Eka Buana, Sidemen, Karangasem, Bali, Indonesia",
    "note": "Natural rock pools / Sidemen area.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Gembleng Waterfall Bali"
  },
  {
    "id": "munduk-waterfalls-trek-17",
    "name": "Munduk Waterfalls Trek",
    "category": "Waterfalls",
    "query": "Munduk Waterfalls Trekking Point, Gobleg, Banjar, Buleleng, Bali, Indonesia",
    "note": "North Bali waterfall trek.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Munduk Waterfalls Trek Bali"
  },
  {
    "id": "taman-dedari-18",
    "name": "Taman Dedari",
    "category": "Sites",
    "query": "Taman Dedari, Kedewatan, Ubud, Gianyar, Bali, Indonesia",
    "note": "Giant-statue garden / restaurant.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Taman Dedari Bali"
  },
  {
    "id": "kelingking-beach-19",
    "name": "Kelingking Beach",
    "category": "Sites",
    "query": "Kelingking Beach, Nusa Penida, Klungkung, Bali, Indonesia",
    "note": "Nusa Penida day-trip stop.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Kelingking Beach",
    "imageQuery": "Kelingking Beach Bali"
  },
  {
    "id": "lahangan-sweet-20",
    "name": "Lahangan Sweet",
    "category": "Sites",
    "query": "Lahangan Sweet, Bunutan, Abang, Karangasem, Bali, Indonesia",
    "note": "Gate / Mount Agung photo viewpoint.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Lahangan Sweet Bali"
  },
  {
    "id": "mount-batur-21",
    "name": "Mount Batur",
    "category": "Sites",
    "query": "Mount Batur, Kintamani, Bangli, Bali, Indonesia",
    "note": "Sunrise hike.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Mount Batur",
    "imageQuery": "Mount Batur Bali"
  },
  {
    "id": "batur-natural-hot-spring-22",
    "name": "Batur Natural Hot Spring",
    "category": "Sites",
    "query": "Batur Natural Hot Spring, Toya Bungkah, Kintamani, Bangli, Bali, Indonesia",
    "note": "Pair after the Mount Batur sunrise.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Batur Natural Hot Spring Bali"
  },
  {
    "id": "papa-nyoman-reflexology-23",
    "name": "Papa Nyoman Reflexology",
    "category": "Activities",
    "query": "Papa Nyoman Reflexology, Ubud, Bali, Indonesia",
    "note": "Sandat Bali. Walk-in; come before 09:30. ~20 min. +62 877-6171-5629",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Papa Nyoman Reflexology Ubud Bali"
  },
  {
    "id": "aquam-spa-seaweed-baths-24",
    "name": "Aquam Spa & Seaweed Baths",
    "category": "Spa",
    "query": "Aquam Spa and Seaweed Baths, Nusa Lembongan, Bali, Indonesia",
    "note": "Seaweed spa; Nusa Lembongan.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Aquam Spa & Seaweed Baths Bali"
  },
  {
    "id": "koli-koli-bali-25",
    "name": "Koli-Koli Bali",
    "category": "Spa",
    "query": "Koli-Koli Bali, Sidemen, Karangasem, Bali, Indonesia",
    "note": "Plunge pools / Sidemen.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Koli-Koli Bali Bali"
  },
  {
    "id": "shosan-holistic-spa-26",
    "name": "SHOSAN Holistic Spa",
    "category": "Spa",
    "query": "SHOSAN Holistic Spa, Pererenan, Badung, Bali, Indonesia",
    "note": "Ayurvedic head spa.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "SHOSAN Holistic Spa Bali"
  },
  {
    "id": "amed-snorkeling-turtles-27",
    "name": "Amed Snorkeling / Turtles",
    "category": "Activities",
    "query": "Amed Beach, Amed, Karangasem, Bali, Indonesia",
    "note": "Snorkeling / turtles.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Amed Snorkeling / Turtles Bali"
  },
  {
    "id": "manta-point-nusa-penida-28",
    "name": "Manta Point, Nusa Penida",
    "category": "Activities",
    "query": "Manta Point, Nusa Penida, Klungkung, Bali, Indonesia",
    "note": "Best kept as its own manta-ray stop rather than grouping it with Amed.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Manta Point, Nusa Penida Bali"
  },
  {
    "id": "virgin-beach-29",
    "name": "Virgin Beach",
    "category": "Activities",
    "query": "Virgin Beach, Karangasem, Bali, Indonesia",
    "note": "East Bali beach stop.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Virgin Beach, Bali",
    "imageQuery": "Virgin Beach Bali"
  },
  {
    "id": "bali-zoo-30",
    "name": "Bali Zoo",
    "category": "Activities",
    "query": "Bali Zoo, Singapadu, Sukawati, Gianyar, Bali, Indonesia",
    "note": "Capybara café / experience.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "Bali Zoo",
    "imageQuery": "Bali Zoo Bali"
  },
  {
    "id": "make-your-own-batik-31",
    "name": "Make Your Own Batik",
    "category": "Activities",
    "query": "I Nyoman Warta Batik Class, Ubud, Bali, Indonesia",
    "note": "Hands-on batik class in/near Ubud.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Make Your Own Batik Bali"
  },
  {
    "id": "swing-heaven-32",
    "name": "Swing Heaven",
    "category": "Activities",
    "query": "Swing Heaven Bali, Bongkasa, Abiansemal, Badung, Bali, Indonesia",
    "note": "Jungle swings / photo spot.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Swing Heaven Bali"
  },
  {
    "id": "blangsingah-glass-bridge-rainbow-slide-33",
    "name": "Blangsingah Glass Bridge + Rainbow Slide",
    "category": "Activities",
    "query": "Blangsingah Glass Bridge, Saba, Blahbatuh, Gianyar, Bali, Indonesia",
    "note": "Glass bridge + rainbow slide.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Blangsingah Glass Bridge + Rainbow Slide Bali"
  },
  {
    "id": "bali-pulina-coffee-plantation-34",
    "name": "Bali Pulina Coffee Plantation",
    "category": "Activities",
    "query": "Bali Pulina Coffee Plantation, Sebatu, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Coffee plantation / tasting.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Bali Pulina Coffee Plantation Bali"
  },
  {
    "id": "tis-cafe-35",
    "name": "TIS Cafe",
    "category": "Food",
    "query": "TIS Cafe, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Rice-terrace view.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "TIS Cafe Bali"
  },
  {
    "id": "cretya-ubud-36",
    "name": "Cretya Ubud",
    "category": "Food",
    "query": "Cretya Ubud, Alas Harum, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "View / pools; same complex as Alas Harum.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Cretya Ubud Bali"
  },
  {
    "id": "omma-dayclub-bali-37",
    "name": "Omma Dayclub Bali",
    "category": "Food",
    "query": "Omma Dayclub Bali, Tegenungan Waterfall, Kemenuh, Gianyar, Bali, Indonesia",
    "note": "Waterfall view.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Omma Dayclub Bali Bali"
  },
  {
    "id": "hanging-restaurant-bar-38",
    "name": "Hanging Restaurant & Bar",
    "category": "Food",
    "query": "Hanging Restaurant and Bar, Sekumpul, Buleleng, Bali, Indonesia",
    "note": "Sekumpul waterfall view / North Bali.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Hanging Restaurant & Bar Bali"
  },
  {
    "id": "7am-bakers-7pm-diners-ubud-39",
    "name": "7AM Bakers | 7PM Diners Ubud",
    "category": "Food",
    "query": "7AM Bakers 7PM Diners Ubud, Ubud, Bali, Indonesia",
    "note": "Bakery / café.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "7AM Bakers | 7PM Diners Ubud Bali"
  },
  {
    "id": "mamu-garden-cafe-lounge-40",
    "name": "MAMU Garden Cafe & Lounge",
    "category": "Food",
    "query": "MAMU Garden Cafe and Lounge, Ubud, Bali, Indonesia",
    "note": "Garden café.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "MAMU Garden Cafe & Lounge Bali"
  },
  {
    "id": "warung-pulau-kelapa-41",
    "name": "Warung Pulau Kelapa",
    "category": "Food",
    "query": "Warung Pulau Kelapa, Kedewatan, Ubud, Bali, Indonesia",
    "note": "Indonesian food / garden setting.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Warung Pulau Kelapa Bali"
  },
  {
    "id": "sayan-valley-42",
    "name": "Sayan Valley",
    "category": "Food",
    "query": "Sayan Valley Sunset Restaurant, Sayan, Ubud, Bali, Indonesia",
    "note": "Cute small bites / valley view.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Sayan Valley Bali"
  },
  {
    "id": "akasa-at-jumeirah-bali-43",
    "name": "Akasa at Jumeirah Bali",
    "category": "Food",
    "query": "Akasa Jumeirah Bali, Pecatu, Uluwatu, Bali, Indonesia",
    "note": "Cliffside; far south of Ubud.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Akasa at Jumeirah Bali Bali"
  },
  {
    "id": "terra-verte-ubud-44",
    "name": "Terra Verte Ubud",
    "category": "Food",
    "query": "Terra Verte Restaurant Ubud, Tegallalang, Gianyar, Bali, Indonesia",
    "note": "Ubud-area restaurant / view.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Terra Verte Ubud Bali"
  },
  {
    "id": "d-tukad-river-club-45",
    "name": "D'tukad River Club",
    "category": "Food",
    "query": "Dtukad River Club Bali, Saba, Gianyar, Bali, Indonesia",
    "note": "River / waterfall club.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "D'tukad River Club Bali"
  },
  {
    "id": "menikamati-coffee-46",
    "name": "Menikamati Coffee",
    "category": "Needs Confirmation",
    "query": "Menikamati Coffee, Bali, Indonesia",
    "note": "Name needs confirmation; keep this card so we do not lose it.",
    "done": false,
    "lat": null,
    "lng": null,
    "custom": false,
    "photoUrl": "",
    "photoThumbUrl": "",
    "photoLink": "",
    "photoSource": "",
    "wikiTitle": "",
    "imageQuery": "Menikamati Coffee Bali"
  }
];
